#!/usr/bin/env python

import os
import shutil
import sys
from diffusers import StableDiffusionPipeline

# append project directory to path so predict.py can be imported
sys.path.append('.')

from predict import MODEL_NAME, MODEL_CACHE

if os.path.exists(MODEL_CACHE):
    shutil.rmtree(MODEL_CACHE)
os.makedirs(MODEL_CACHE, exist_ok=True)

pipe = StableDiffusionPipeline.from_pretrained(
    MODEL_NAME,
    cache_dir=MODEL_CACHE
)
